-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 09:22:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema funko_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema funko_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `funko_schema` DEFAULT CHARACTER SET utf8 ;
USE `funko_schema` ;

-- -----------------------------------------------------
-- Table `funko_schema`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `category_description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;

INSERT INTO `category` (`category_id`, `category_name`, `category_description`) VALUES
(1, 'Funkos', 'Figuras coleccionables Funko Pop'),
(2, 'Indumentaria', 'Remeras de anime, series, peliculas y más'),
(3, 'Pins', 'Llaveros coleccionables');

-- -----------------------------------------------------
-- Table `funko_schema`.`licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`licence` (
  `licence_id` INT NOT NULL AUTO_INCREMENT,
  `licence_name` VARCHAR(45) NOT NULL,
  `licence_description` VARCHAR(255) NOT NULL,
  `licence_image` VARCHAR(255) NULL,
  PRIMARY KEY (`licence_id`))
ENGINE = InnoDB;

INSERT INTO `licence` (`licence_id`, `licence_name`, `licence_description`, `licence_image`) VALUES
(1, 'Pokemon', 'Atrapa todos los que puedas y disfruta de una colección llena de amigos.', '/img/pokemon/pk-cover.jpg'),
(2, 'Star Wars', 'Disfruta de una saga que sigue agregando personajes a su colección.', '/img/star-wars/st-cover.jpg'),
(3, 'Harry Potter', 'Revive los recuerdos de una saga llena de magia y encanto.', '/img/harry-potter/hp-cover.jpg');
-- -----------------------------------------------------
-- Table `funko_schema`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(60) NOT NULL,
  `product_description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NOT NULL,
  `sku` VARCHAR(30) NOT NULL,
  `dues` INT NOT NULL,
  `image_front` VARCHAR(200) NOT NULL,
  `image_back` VARCHAR(200) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `category_id` INT NOT NULL,
  `licence_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_product_licence1_idx` (`licence_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `funko_schema`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_licence1`
    FOREIGN KEY (`licence_id`)
    REFERENCES `funko_schema`.`licence` (`licence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `product` (`product_id`, `product_name`, `product_description`, `price`, `stock`, `discount`, `sku`, `dues`, `image_front`, `image_back`, `create_time`, `licence_id`, `category_id`) VALUES
(1, 'Baby Yoda Blueball', 'Figura coleccionable de Baby Yoda (Grogu) - The Mandalorian Saga, edición limitada.', '1799.99', 8, 10, 'STW001001', 3, '/star-wars/baby-yoda-1.webp', '/star-wars/baby-yoda-box.webp', '2023-06-27 23:33:21', 2, 1),
(3, 'Luke Skylwalker & Grogu', 'Figura coleccionable de Luke Skylwalker & Grogu - The Mandalorian Saga.', '2399.99', 8, 10, 'STW001003', 3, '/star-wars/luke-1.webp', '/star-wars/luke-box.webp', '2023-06-27 23:33:21', 2, 1),
(4, 'Stormtrooper Lightsaber', 'Figura coleccionable de Stormtrooper Lightsaber - Star Wars Saga.', '1799.99', 8, 10, 'STW001004', 3, '/star-wars/trooper-1.webp', '/star-wars/trooper-box.webp', '2023-06-27 23:33:21', 2, 1),
(5, 'Charmander Smiley', 'Figura coleccionable de Charmander - Pokemon Saga.', '1799.99', 8, 10, 'PKM001001', 3, '/pokemon/charmander-1.webp', '/pokemon/charmander-box.webp', '2023-06-27 23:33:21', 1, 1),
(6, 'Dragonite Hi!', 'Figura coleccionable de Dragonite - Pokemon Saga.', '1799.99', 8, 10, 'PKM001002', 3, '/pokemon/dragonite-1.webp', '/pokemon/dragonite-box.webp', '2023-06-27 23:33:21', 1, 1),
(7, 'Pidgeotto Flying', 'Figura coleccionable de Pidgeotto - Pokemon Saga.', '1799.99', 8, 10, 'PKM00103', 3, '/pokemon/pidgeotto-1.webp', '/pokemon/pidgeotto-box.webp', '2023-06-27 23:33:21', 1, 1),
(8, 'Pikachu Smiley', 'Figura coleccionable de Pikachu - Pokemon Saga.', '1799.99', 8, 10, 'PKM001004', 3, '/pokemon/pikachu-1.webp', '/pokemon/pikachu-box.webp', '2023-06-27 23:33:21', 1, 1),
(9, 'Vulpix Fancy', 'Figura coleccionable de Vulpix - Pokemon Saga.', '99.99', 8, 10, 'PKM001005', 3, '/pokemon/vulpix-1.webp', '/pokemon/vulpix-box.webp', '2023-06-27 23:33:21', 1, 1),
(10, 'Harry Potter & Hegwid', 'Figura coleccionable de Harry Potter & Hegwid - Harry Potter Saga.', '1799.99', 11, 10, 'HPT0', 9, '/harry-potter/harry-1.webp', '/harry-potter/harry-box.webp', '2023-06-27 23:33:21', 3, 1),
(11, 'Herminione Ball Dress', 'Figura coleccionable de Herminione - Harry Potter Saga.', '1799.99', 8, 10, 'HPT001002', 3, '/harry-potter/hermione-1.webp', '/harry-potter/hermione-box.webp', '2023-06-27 23:33:21', 3, 1),
(12, 'Luna Lovegood Lion Mask', 'Figura coleccionable de Luna Lovegood - Harry Potter Saga.', '1799.99', 8, 10, 'HPT001003', 3, '/harry-potter/luna-1.webp', '/harry-potter/luna-box.webp', '2023-06-27 23:33:21', 3, 1),
(13, 'Snape Patronus', 'Figura coleccionable de Snape Patronus - Harry Potter Saga.', '1799.99', 13, 10, 'HPT001004', 3, '/harry-potter/snape-patronus-1.webp', '/harry-potter/snape-patronus-box.webp', '2023-06-27 23:33:21', 3, 1);

-- -----------------------------------------------------
-- Table `funko_schema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
